version: "3"

services:
  splunk:
    build:
      context: nginx/
    ports:
      - 5000:5000
  
  nginx:
    build:
      context: nginx/

    ports:
      - 80:443
    depends_on:
       - smeiling

  smeiling:
     build:
       context: smeiling/
     volumes:
       - ./config/:/app/config