app:
  name: vodademo
  host: 35.187.77.111
  port: 443
  ssl: yes

  dashboards:
    Vodafone:
      app: rot_smart_homes_app
      name: smeiling_dashboard_vodafone_demo_v10

  backend:
    debug: yes
    secret_key: republic

  proxy:
    name: proxy
    host: 37.48.244.182
    port: 8000
    scheme: http
    username: vodademo
    password: b98puxPJinkQ

  style:
    logos:
      smeiling: app/SmEILing.png
      republic: app/republic_logo.png
      partner: app/vodafone.png

    stylesheets:
      - app/content/republic.css
